# Generated by Django 3.2.23 on 2024-07-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('cellphone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('job', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Operations', 'Operations')], max_length=50)),
                ('date', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
    ]
